name: Deploy Backend to OCI

on:
  push:
    branches:
      - master  # Se dispara automáticamente al mergear o pushear a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to OCI via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /opt/lince-teams
            git pull origin main
            npm install --omit=dev
            sudo systemctl restart lince-teams
